"""Tests for ``hermes-mordred uninstall``.

Each test builds a Hermes home, snapshots its "before Mordred" files, then
installs Mordred into it with the real writers and encryption engines (software
fakes stand in for the Secure Enclave and Keychain): ``configure``'s policy
writer, ``network init``'s ``.env`` writer, ``desktop install``, and
``encryption enable config|env|memory``. After ``uninstall`` Hermes's files
must be back to what they were.
"""

from __future__ import annotations

import subprocess
from collections.abc import Sequence
from dataclasses import dataclass, field
from pathlib import Path

import pytest
from ruamel.yaml import YAML

from mordred_hermes.desktop import install as desktop_install
from mordred_hermes.keyvault import _identity, _runtime_probe
from mordred_hermes.keyvault._config_bootstrap import _marker_path
from mordred_hermes.keyvault._memory_hook import memory_marker_path
from mordred_hermes.keyvault.memory_crypto import is_sealed
from mordred_hermes.wizard import (
    _runtime_gate,
    config_decrypt_cli,
    encryption_cli,
    env_decrypt_cli,
    memory_cli,
    uninstall_cli,
)
from mordred_hermes.wizard._uninstall_config import plan_config_cleanup
from mordred_hermes.wizard._uninstall_hermes_env import (
    HermesEnv,
    classify_helpers,
    classify_launchers,
    detect_hermes_env,
)
from mordred_hermes.wizard.env_file_writer import DotEnvFileWriter
from mordred_hermes.wizard.policy_writer import PolicySnapshot, PolicyWriter
from mordred_hermes.wizard.uninstall_cli import UninstallContext, UninstallOptions, run_uninstall

from ._helpers import _init_empty_vault
from ._keyvault_fakes import FakeAnchorStore, FakeBackend

# Written the way Mordred's round-trip writer serializes YAML, so the restored
# file can be compared byte for byte (see test_config_yaml_is_byte_identical).
_CONFIG = """\
_config_version: 22
model:
  default: some-model
  provider: openrouter
plugins:
  clone_timeout_seconds: 300
  enabled:
    - other_plugin
  disabled: []
memory:
  memory_enabled: true
  user_char_limit: 1375
"""
_ENV = "OPENROUTER_API_KEY=sk-test\n# a comment\nOTHER=value\n"
_MEMORIES = {"MEMORY.md": "- the user likes tea\n", "USER.md": "- name: Ada\n"}
_LAUNCHER = '#!/usr/bin/env bash\n# Generated by the hermes-mordred installer. Safe to delete.\nexec x "$@"\n'


@dataclass
class FakeRunner:
    """Stands in for uv / codesign / the Hermes launcher; records every call."""

    installed: set[str] = field(default_factory=lambda: {"hermes-mordred"})
    calls: list[list[str]] = field(default_factory=list)
    uninstall_rc: int = 0
    codesign: str = ""

    def __call__(self, argv: Sequence[str]) -> subprocess.CompletedProcess[str]:
        argv = list(argv)
        self.calls.append(argv)
        rc, out, err = 64, "", ""
        if argv[1:3] == ["pip", "show"]:
            rc = 0 if argv[-1] in self.installed else 1
        elif argv[1:3] == ["pip", "uninstall"]:
            rc = self.uninstall_rc
            if rc == 0:
                self.installed.clear()
            out = "Uninstalled 1 package"
        elif argv[0] == "codesign":
            rc, err = 0, self.codesign
        return subprocess.CompletedProcess(argv, rc, out, err)

    @property
    def uninstalls(self) -> list[list[str]]:
        return [call for call in self.calls if call[1:3] == ["pip", "uninstall"]]


@dataclass
class Installed:
    home: Path
    root: Path
    user_home: Path
    backend: FakeBackend
    store: FakeAnchorStore
    runner: FakeRunner
    hermes_python: Path
    before: dict[str, bytes]

    def context(self, **overrides: object) -> UninstallContext:
        values: dict[str, object] = {
            "home": self.home,
            "vault_root": self.root,
            "user_home": self.user_home,
            "platform": "darwin",
            "backend": self.backend,
            "store": self.store,
            "which": lambda _name: None,
            "runner": self.runner,
            "stamp": "20260101-000000",
            "interactive": False,
            "gateways": lambda _home: [],
            "telegram_forget": lambda: 0,
            "keyvault_reset": lambda _home: 0,
        }
        values.update(overrides)
        return UninstallContext(**values)  # type: ignore[arg-type]


def _snapshot(home: Path) -> dict[str, bytes]:
    files = {"config.yaml": (home / "config.yaml").read_bytes(), ".env": (home / ".env").read_bytes()}
    for name in _MEMORIES:
        files[f"memories/{name}"] = (home / "memories" / name).read_bytes()
    return files


def _yaml(path: Path) -> object:
    return YAML(typ="safe").load(path.read_text(encoding="utf-8"))


@pytest.fixture(autouse=True)
def _quiet_runtime(monkeypatch: pytest.MonkeyPatch) -> None:
    """Capable runtime, no running gateways, no process-table reads."""
    monkeypatch.setattr(encryption_cli, "memory_runtime_available", lambda: (True, "seam A"))
    monkeypatch.setattr(_runtime_probe, "discover_running_gateway_runtimes", lambda **_kw: [])
    monkeypatch.setattr(_runtime_probe, "discover_runtime_python", lambda **_kw: None)
    monkeypatch.setattr(_runtime_gate, "_default_gateway_discovery", lambda *, home: [])


def _hermes_env(home: Path) -> Path:
    """A virtualenv-shaped Hermes environment holding the console script."""
    bin_dir = home / "hermes-agent" / "venv" / "bin"
    bin_dir.mkdir(parents=True)
    (home / "hermes-agent" / "venv" / "pyvenv.cfg").write_text("home = /usr/bin\n", encoding="utf-8")
    for name in ("python3", "hermes-mordred"):
        (bin_dir / name).write_text("#!/bin/sh\nexit 0\n", encoding="utf-8")
        (bin_dir / name).chmod(0o755)
    uv = home / "tools" / "uv-0.1.0" / "uv"
    uv.parent.mkdir(parents=True)
    uv.write_text("#!/bin/sh\nexit 0\n", encoding="utf-8")
    uv.chmod(0o755)
    return bin_dir / "python3"


@pytest.fixture
def installed(tmp_path: Path) -> Installed:
    home, user_home = tmp_path / "hermes", tmp_path / "user"
    home.mkdir()
    (home / "config.yaml").write_text(_CONFIG, encoding="utf-8")
    (home / ".env").write_text(_ENV, encoding="utf-8")
    (home / "memories").mkdir()
    for name, text in _MEMORIES.items():
        (home / "memories" / name).write_text(text, encoding="utf-8")
    before = _snapshot(home)
    hermes_python = _hermes_env(home)
    launcher = user_home / ".local" / "bin" / "hermes-mordred"
    launcher.parent.mkdir(parents=True)
    launcher.write_text(_LAUNCHER, encoding="utf-8")

    # --- install Mordred the way its commands do -----------------------------
    writer = PolicyWriter(config_path=home / "config.yaml", policy_json_path=home / "mordred" / "policy.json")
    writer.write(PolicySnapshot(policy="strict", audit_log_path=str(home / "mordred" / "audit.log")))
    DotEnvFileWriter().upsert(home / ".env", key="MORDRED_MULLVAD_ACCOUNT", value="1234567890")
    assert desktop_install.install(home) == 0

    root = home / "mordred" / "vault"
    backend, store = FakeBackend(), FakeAnchorStore()
    _init_empty_vault(root, backend, store)
    kwargs = {"home": home, "root": root, "backend": backend, "store": store, "force_runtime_unverified": True}
    assert config_decrypt_cli.enable(platform="darwin", **kwargs) == 0  # type: ignore[arg-type]
    (home / "config.yaml").unlink()  # a Hermes session's reseal-on-exit removes the plaintext
    assert env_decrypt_cli.enable(platform="darwin", **kwargs) == 0  # type: ignore[arg-type]
    assert memory_cli.enable(platform="darwin", **kwargs) == 0  # type: ignore[arg-type]

    assert not (home / ".env").exists() and not (home / "config.yaml").exists()
    assert all(is_sealed((home / "memories" / name).read_bytes()) for name in _MEMORIES)
    return Installed(home, root, user_home, backend, store, FakeRunner(), hermes_python, before)


# -----------------------------------------------------------------------------
# The full round trip
# -----------------------------------------------------------------------------
class TestFullUninstall:
    def test_restores_hermes_files_and_removes_mordred(
        self, installed: Installed, capsys: pytest.CaptureFixture[str]
    ) -> None:
        home = installed.home
        rc = run_uninstall(installed.context(), UninstallOptions(yes=True))
        out = capsys.readouterr().out

        assert rc == 0, out
        # a. plaintext is back, byte for byte.
        assert (home / ".env").read_bytes() == installed.before[".env"]
        for name in _MEMORIES:
            assert (home / "memories" / name).read_bytes() == installed.before[f"memories/{name}"]
        assert not _marker_path(home).exists()
        assert not memory_marker_path(home).exists()
        # b. config.yaml has nothing of Mordred's left.
        assert _yaml(home / "config.yaml") == _yaml_text(installed.before["config.yaml"])
        assert list(home.glob("config.yaml.mordred-uninstall-*.bak"))
        assert not (home / "plugins" / "mordred").exists()
        assert not (home / ".env.lock").exists()
        saved = (home / "mordred" / "uninstall" / "env-removed-20260101-000000.env").read_text(encoding="utf-8")
        assert "HERMES_MEMORY_KEY=" in saved and "MORDRED_MULLVAD_ACCOUNT=1234567890" in saved
        # c. the installer's launcher is gone.
        assert not (installed.user_home / ".local" / "bin" / "hermes-mordred").exists()
        # d. the package is uninstalled from Hermes's environment, last.
        assert installed.runner.uninstalls == [
            [
                str(home / "tools" / "uv-0.1.0" / "uv"),
                "pip",
                "uninstall",
                "--python",
                str(installed.hermes_python),
                "hermes-mordred",
            ]
        ]
        # e. data is kept and listed.
        assert installed.root.is_dir()
        assert "Kept (not deleted)" in out and str(installed.root) in out

    def test_config_yaml_is_byte_identical(self, installed: Installed) -> None:
        assert run_uninstall(installed.context(), UninstallOptions(yes=True)) == 0
        assert (installed.home / "config.yaml").read_bytes() == installed.before["config.yaml"]

    def test_unlocks_the_vault_once(self, installed: Installed) -> None:
        installed.backend.calls.clear()
        assert run_uninstall(installed.context(), UninstallOptions(yes=True)) == 0
        assert [call for call in installed.backend.calls if call[0] == "ecdh"] == [
            ("ecdh", _identity.vault_identity(installed.root))
        ]

    def test_second_run_changes_nothing(self, installed: Installed, capsys: pytest.CaptureFixture[str]) -> None:
        assert run_uninstall(installed.context(), UninstallOptions(yes=True)) == 0
        after_first = _snapshot(installed.home)
        backups = sorted(installed.home.glob("config.yaml.mordred-uninstall-*.bak"))
        capsys.readouterr()

        assert run_uninstall(installed.context(stamp="20260102-000000"), UninstallOptions(yes=True)) == 0

        assert "nothing to do" in capsys.readouterr().out
        assert _snapshot(installed.home) == after_first
        assert sorted(installed.home.glob("config.yaml.mordred-uninstall-*.bak")) == backups
        assert len(installed.runner.uninstalls) == 1

    def test_dry_run_changes_nothing(self, installed: Installed, capsys: pytest.CaptureFixture[str]) -> None:
        tree_before = _tree(installed.home)

        assert run_uninstall(installed.context(), UninstallOptions(dry_run=True)) == 0

        out = capsys.readouterr().out
        assert _tree(installed.home) == tree_before
        assert installed.runner.uninstalls == []
        assert "Dry run: nothing was changed." in out
        for expected in ("config: vault-managed", "memory: 2 sealed", "env: vault-managed", "config.yaml is sealed"):
            assert expected in out


def _yaml_text(raw: bytes) -> object:
    return YAML(typ="safe").load(raw.decode("utf-8"))


def _tree(root: Path) -> dict[str, bytes | None]:
    return {
        str(path.relative_to(root)): (path.read_bytes() if path.is_file() else None) for path in sorted(root.rglob("*"))
    }


# -----------------------------------------------------------------------------
# Refusals: nothing may be removed when Hermes's files cannot be restored
# -----------------------------------------------------------------------------
class TestRefusals:
    def _assert_nothing_removed(self, installed: Installed) -> None:
        home = installed.home
        assert (home / "plugins" / "mordred").is_dir()
        assert (installed.user_home / ".local" / "bin" / "hermes-mordred").exists()
        assert installed.runner.uninstalls == []
        assert not list(home.glob("config.yaml.mordred-uninstall-*.bak"))

    def test_stops_when_memory_cannot_be_decrypted(
        self, installed: Installed, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
    ) -> None:
        monkeypatch.setattr(memory_cli, "_memory_key_from_vault", lambda **_kw: None)

        rc = run_uninstall(installed.context(), UninstallOptions(yes=True))

        assert rc == 1
        assert "memory could not be restored" in capsys.readouterr().err
        self._assert_nothing_removed(installed)
        assert all(is_sealed((installed.home / "memories" / name).read_bytes()) for name in _MEMORIES)
        assert memory_marker_path(installed.home).exists()

    def test_stops_when_the_vault_cannot_be_opened(
        self, installed: Installed, capsys: pytest.CaptureFixture[str]
    ) -> None:
        rc = run_uninstall(installed.context(backend=FakeBackend()), UninstallOptions(yes=True))

        assert rc == 1
        assert "the vault could not be opened" in capsys.readouterr().err
        self._assert_nothing_removed(installed)
        assert not (installed.home / ".env").exists()
        assert _marker_path(installed.home).exists()

    def test_offers_the_recovery_passphrase_when_the_device_key_fails(self, installed: Installed) -> None:
        from ._keyvault_fakes import FixedPassphrasePromptIO

        rc = run_uninstall(
            installed.context(backend=FakeBackend(), prompt_io=FixedPassphrasePromptIO("correct horse battery staple")),
            UninstallOptions(yes=True),
        )

        assert rc == 0
        assert (installed.home / ".env").read_bytes() == installed.before[".env"]

    def test_non_interactive_without_yes_changes_nothing(
        self, installed: Installed, capsys: pytest.CaptureFixture[str]
    ) -> None:
        rc = run_uninstall(installed.context(), UninstallOptions())

        assert rc == 1
        assert "--yes" in capsys.readouterr().err
        self._assert_nothing_removed(installed)
        assert not (installed.home / ".env").exists()

    def test_failed_package_uninstall_is_reported(
        self, installed: Installed, capsys: pytest.CaptureFixture[str]
    ) -> None:
        installed.runner.uninstall_rc = 1

        rc = run_uninstall(installed.context(), UninstallOptions(yes=True))

        assert rc == 1
        assert "pip uninstall failed" in capsys.readouterr().err
        assert (installed.home / ".env").read_bytes() == installed.before[".env"]


# -----------------------------------------------------------------------------
# --purge-data
# -----------------------------------------------------------------------------
class _TypedPrompt:
    def __init__(self, text: str) -> None:
        self.text = text
        self.asked: list[str] = []

    def ask_bool(self, label: str, default: bool, *, description: str | None = None) -> bool:
        self.asked.append(label)
        return True

    def ask_text(self, label: str, default: str = "", *, description: str | None = None) -> str:
        self.asked.append(label)
        return self.text


class TestEraseEncrypted:
    def test_erases_without_decrypting_or_unlocking(
        self, installed: Installed, capsys: pytest.CaptureFixture[str]
    ) -> None:
        home = installed.home
        installed.backend.calls.clear()
        prompt = _TypedPrompt(uninstall_cli.PURGE_PHRASE)
        ctx = installed.context(prompt_io=prompt, telegram_forget=lambda: 0, keyvault_reset=lambda _home: 0)

        rc = run_uninstall(ctx, UninstallOptions(yes=True, erase_encrypted=True))

        out = capsys.readouterr().out
        assert rc == 0, out
        assert "ERASE encrypted data WITHOUT decrypting" in out
        assert len(prompt.asked) == 1  # the typed "delete my data"
        # Nothing was decrypted: no vault unlock, no plaintext written back.
        assert not [call for call in installed.backend.calls if call[0] == "ecdh"]
        assert not (home / ".env").exists() and not (home / "config.yaml").exists()
        assert not any((home / "memories" / name).exists() for name in _MEMORIES)
        # Mordred and all its data are gone.
        assert not (home / "mordred").exists()
        assert not (home / "plugins" / "mordred").exists()
        assert installed.runner.uninstalls

    def test_erase_needs_the_typed_phrase(self, installed: Installed) -> None:
        ctx = installed.context(prompt_io=_TypedPrompt("yes"))
        assert run_uninstall(ctx, UninstallOptions(yes=True, erase_encrypted=True)) == 1
        assert all(is_sealed((installed.home / "memories" / n).read_bytes()) for n in _MEMORIES)
        assert (installed.home / "mordred" / "vault").is_dir()


class TestPurge:
    def test_deletes_data_after_typed_confirmation(self, installed: Installed) -> None:
        telegram = installed.home / "mordred" / "telegram"
        telegram.mkdir(parents=True)
        (telegram / "credentials.sealed").write_bytes(b"MTC1")
        (installed.home / "mordred" / "keyvault").mkdir()
        events: list[str] = []

        def telegram_forget() -> int:
            events.append("telegram")
            return 0

        def keyvault_reset(_home: Path) -> int:
            events.append("keyvault")
            return 0

        prompt = _TypedPrompt(uninstall_cli.PURGE_PHRASE)
        ctx = installed.context(prompt_io=prompt, telegram_forget=telegram_forget, keyvault_reset=keyvault_reset)

        rc = run_uninstall(ctx, UninstallOptions(yes=True, purge_data=True))

        assert rc == 0
        assert events == ["telegram", "keyvault"]
        assert len(prompt.asked) == 1  # --yes skips the plain question, never the typed one
        assert not (installed.home / "mordred").exists()
        label = _identity.vault_identity(installed.root)
        assert installed.store.read(label) is None
        assert ("delete", label) in installed.backend.calls
        assert (installed.home / ".env").read_bytes() == installed.before[".env"]

    def test_undeletable_device_key_is_reported_with_manual_steps(
        self, installed: Installed, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
    ) -> None:
        def refuse(_key_id: str) -> None:
            raise RuntimeError("owner ACL")

        monkeypatch.setattr(installed.backend, "delete_enclave_key", refuse)
        ctx = installed.context(prompt_io=_TypedPrompt(uninstall_cli.PURGE_PHRASE))

        assert run_uninstall(ctx, UninstallOptions(yes=True, purge_data=True)) == 0

        err = capsys.readouterr().err
        assert "Keychain Access" in err and "mordred-hermes.wrsw." in err
        assert not (installed.home / "mordred").exists()

    def test_wrong_phrase_changes_nothing(self, installed: Installed) -> None:
        rc = run_uninstall(
            installed.context(prompt_io=_TypedPrompt("yes")), UninstallOptions(yes=True, purge_data=True)
        )

        assert rc == 1
        assert installed.root.is_dir()
        assert not (installed.home / ".env").exists()
        assert installed.runner.uninstalls == []

    def test_keyvault_reset_failure_keeps_the_data(self, installed: Installed) -> None:
        (installed.home / "mordred" / "keyvault").mkdir()
        ctx = installed.context(prompt_io=_TypedPrompt(uninstall_cli.PURGE_PHRASE), keyvault_reset=lambda _home: 1)

        assert run_uninstall(ctx, UninstallOptions(yes=True, purge_data=True)) == 1
        assert (installed.home / "mordred" / "keyvault").is_dir()
        assert installed.runner.uninstalls == []


# -----------------------------------------------------------------------------
# Pieces
# -----------------------------------------------------------------------------
class TestConfigCleanup:
    def test_reports_what_it_cannot_restore(self, tmp_path: Path) -> None:
        path = tmp_path / "config.yaml"
        path.write_text(
            "model:\n  provider: mordred-local\nplugins:\n  enabled:\n    - mordred_network\n    - x\n"
            "  mordred_network:\n    default_path: tor\nmemory:\n  encryption:\n    enabled: false\n",
            encoding="utf-8",
        )

        plan = plan_config_cleanup(path)

        assert plan.removed == ["plugins.enabled: mordred_network", "plugins.mordred_network", "memory.encryption"]
        assert plan.unknowns == ["model.provider: mordred-local"]

    def test_unparseable_config_is_left_alone(self, tmp_path: Path) -> None:
        path = tmp_path / "config.yaml"
        path.write_text("plugins: [unclosed\n", encoding="utf-8")

        plan = plan_config_cleanup(path)

        assert plan.error is not None and not plan.changed


class TestHermesEnvDetection:
    def test_managed_launcher_reports_its_environment(self, tmp_path: Path) -> None:
        home = tmp_path / "hermes"
        env_root = tmp_path / "installs" / "env" / "venv"
        (env_root / "bin").mkdir(parents=True)
        (env_root / "pyvenv.cfg").write_text("", encoding="utf-8")
        python = env_root / "bin" / "python"
        python.write_text("", encoding="utf-8")
        python.chmod(0o755)
        launcher = home / "hermes-agent" / ".hermes" / "bin" / "hermes"
        launcher.parent.mkdir(parents=True)
        launcher.write_text("#!/bin/sh\nexec /opt/python3 -I -c 'boot' \"$@\"\n", encoding="utf-8")
        launcher.chmod(0o755)
        site = f"sys.path = [\n    '{env_root}/lib/python3.14/site-packages',\n]\n"

        def runner(argv: Sequence[str]) -> subprocess.CompletedProcess[str]:
            if list(argv[1:]) == ["--run-module", "site"]:
                return subprocess.CompletedProcess(list(argv), 0, site, "")
            return subprocess.CompletedProcess(list(argv), 1, "", "")

        env = detect_hermes_env(home, which=lambda _name: None, runner=runner)

        assert env.launcher == launcher
        assert env.python == python
        assert env.problem == "uv was not found (not on PATH, not under <home>/tools)"

    def test_foreign_launcher_is_kept_and_symlink_to_console_script_removed(self, tmp_path: Path) -> None:
        user_home = tmp_path / "user"
        bin_dir = user_home / ".local" / "bin"
        bin_dir.mkdir(parents=True)
        python = tmp_path / "venv" / "bin" / "python3"
        env = HermesEnv(launcher=bin_dir / "hermes", python=python, uv=None, installed=())
        (bin_dir / "hermes-mordred").symlink_to(python.parent / "hermes-mordred")

        findings = classify_launchers(env, user_home=user_home)
        assert [(f.path, f.remove) for f in findings] == [(bin_dir / "hermes-mordred", True)]

        (bin_dir / "hermes-mordred").unlink()
        (bin_dir / "hermes-mordred").write_text("#!/bin/sh\necho mine\n", encoding="utf-8")
        assert [f.remove for f in classify_launchers(env, user_home=user_home)] == [False]

    def test_only_the_mordred_built_sekey_helper_is_removable(self, tmp_path: Path) -> None:
        helper = tmp_path / ".local" / "bin" / "mordred-hermes-sekey"
        helper.parent.mkdir(parents=True)
        helper.write_bytes(b"\xcf\xfa")
        mordred = FakeRunner(codesign="Identifier=mordred-hermes-sekey-5555abc\nSignature=adhoc\n")
        other = FakeRunner(codesign="Identifier=com.example.other\nAuthority=Developer ID\n")

        assert classify_helpers(user_home=tmp_path, platform="darwin", runner=mordred)[0].mordred_built
        assert not classify_helpers(user_home=tmp_path, platform="darwin", runner=other)[0].mordred_built

    def test_purge_uses_the_helper_before_removing_it(self, installed: Installed) -> None:
        # Revoking the Telegram session and deleting device keys need the
        # Secure Enclave helper, so it must still exist while the purge runs.
        helper = installed.user_home / ".local" / "bin" / "mordred-hermes-sekey"
        helper.write_bytes(b"\xcf\xfa")
        installed.runner.codesign = "Identifier=mordred-hermes-sekey-1\nSignature=adhoc\n"
        telegram = installed.home / "mordred" / "telegram"
        telegram.mkdir(parents=True)
        (telegram / "credentials.sealed").write_bytes(b"MTC1")
        seen: list[bool] = []

        def telegram_forget() -> int:
            seen.append(helper.exists())
            return 0

        ctx = installed.context(
            prompt_io=_TypedPrompt(uninstall_cli.PURGE_PHRASE),
            telegram_forget=telegram_forget,
            keyvault_reset=lambda _home: 0,
        )

        assert run_uninstall(ctx, UninstallOptions(yes=True, purge_data=True)) == 0
        assert seen == [True]
        assert not helper.exists()

    def test_remove_helper_flag(self, installed: Installed) -> None:
        helper = installed.user_home / ".local" / "bin" / "mordred-hermes-sekey"
        helper.write_bytes(b"\xcf\xfa")
        installed.runner.codesign = "Identifier=mordred-hermes-sekey-1\nSignature=adhoc\n"

        assert run_uninstall(installed.context(), UninstallOptions(yes=True)) == 0
        assert helper.exists()  # kept by default: the kept vault's device key needs it

        helper_home = installed.context(stamp="x")
        assert run_uninstall(helper_home, UninstallOptions(yes=True, remove_helper=True)) == 0
        assert not helper.exists()


@pytest.fixture(autouse=True)
def _macos_key_custody_contract(monkeypatch):
    """These regressions exercise macOS env/vault custody on every CI OS."""
    import mordred_hermes.wizard.memory_cli as module
    from tests._helpers import PlatformSys

    monkeypatch.setattr(module, "sys", PlatformSys("darwin"))
