#!/usr/bin/env bash
# Install hermes-mordred into the Python environment owned by Hermes Agent.
#
# This intentionally follows Hermes's own install layout instead of creating a
# second virtual environment. It installs code only: configuration, key
# creation, and encryption remain explicit follow-up steps.

set -euo pipefail

readonly HERMES_INSTALL_URL="https://hermes-agent.nousresearch.com/install.sh"
readonly HERMES_INSTALL_COMMAND="curl -fsSL ${HERMES_INSTALL_URL} | bash"
# Keep in sync with `[tool.mordred] min-hermes-version` in pyproject.toml;
# tests/test_user_installer.py asserts the two agree.
readonly MIN_HERMES_VERSION="0.13.0"
# The canonical-name floor prevents the permanent 0.0.0.dev0 reservation stub
# from ever replacing a working legacy installation during the release window.
readonly MIN_MORDRED_VERSION="0.1.0a16"
readonly DISTRIBUTION_NAME="hermes-mordred"
readonly LEGACY_DISTRIBUTION_NAME="mordred-hermes"
# User-facing runtime features only. Platform extras are automatic; repository
# development/test extras must never be added to Hermes's production venv.
readonly USER_OPTIONAL_EXTRAS="extension,ethereum,messaging,tor-control,telegram"
readonly LAUNCHER_MARKER='# Generated by the hermes-mordred installer.'
readonly LEGACY_LAUNCHER_MARKER='# Generated by the mordred-hermes installer.'

REQUESTED_EXTRAS=""
REQUESTED_VERSION=""
# --from-source: a local hermes-mordred checkout to install instead of PyPI.
SOURCE_DIR=""
EDITABLE=0
# --uninstall: run the installed CLI's `uninstall` instead of installing.
UNINSTALL=0
UNINSTALL_ARGS=()
INSTALL_OPTION_SEEN=""
# Prefixes fail() messages raised while parsing MORDRED_INSTALL_EXTRAS so an
# error names its actual source instead of looking like a typed argument.
EXTRA_ERROR_PREFIX=""

info() {
  printf 'mordred: %s\n' "$*"
}

warn() {
  printf 'mordred: warning: %s\n' "$*" >&2
}

fail() {
  printf 'mordred: error: %s\n' "$*" >&2
  exit 1
}

usage() {
  # Unquoted heredoc (not <<'EOF'): the feature-extras line is interpolated
  # from USER_OPTIONAL_EXTRAS so this text cannot drift from the whitelist
  # below. Nothing else in this text contains $, `, or \.
  cat <<EOF
Usage: install.sh [OPTIONS]

Install hermes-mordred into the Python environment owned by Hermes Agent.
The platform extra (macos or keyvault) is selected automatically.

Options:
  --with-extension  Add the browser-extension server and Ethereum wallet extras.
  --with-telegram   Add the read-only Telegram importer (includes the extension server).
  --extras LIST     Add comma-separated feature extras, or "all".
  --all-extras      Add every user-facing feature extra.
  --version VERSION Install an exact PyPI release at or above the supported floor.
  --from-source DIR Install from a local hermes-mordred checkout instead of PyPI
                    (for testing unreleased changes).
  --editable        With --from-source: link the checkout instead of copying it,
                    so edits take effect on the next Hermes restart.
  --uninstall       Remove Mordred by running "hermes-mordred uninstall" from
                    Hermes's environment (restores encrypted .env, config.yaml
                    and memories to plaintext first; keeps Mordred's data).
    --dry-run       With --uninstall: only print the plan.
    --yes           With --uninstall: do not ask for confirmation.
    --purge-data    With --uninstall: also delete Mordred's data and keys
                    (asks you to type a confirmation).
    --remove-helper With --uninstall: also remove the Mordred-built native helper.
  -h, --help        Show this help and exit.

Feature extras: ${USER_OPTIONAL_EXTRAS//,/, }

MORDRED_INSTALL_EXTRAS accepts the same comma-separated list, which is useful
when the script is read from standard input.
EOF
}

trim_spaces() {
  local value="$1"
  value="${value#"${value%%[![:space:]]*}"}"
  value="${value%"${value##*[![:space:]]}"}"
  printf '%s\n' "$value"
}

extra_is_requested() {
  local extra="$1"
  case ",${REQUESTED_EXTRAS}," in
    *",${extra},"*) return 0 ;;
  esac
  return 1
}

add_requested_extra() {
  local extra
  extra="$(trim_spaces "$1")"
  if [[ -z "$extra" ]]; then
    fail "${EXTRA_ERROR_PREFIX}the optional-extra list contains an empty name"
  fi

  if [[ "$extra" == "all" ]]; then
    parse_extra_list "$USER_OPTIONAL_EXTRAS"
    return
  fi

  case "$extra" in
    extension | ethereum | messaging | tor-control | telegram) ;;
    macos | keyvault)
      fail "${EXTRA_ERROR_PREFIX}${extra} is selected automatically for the current platform; omit it from --extras"
      ;;
    dev | integration)
      fail "${EXTRA_ERROR_PREFIX}${extra} is for repository development and cannot be installed into Hermes's runtime environment"
      ;;
    *)
      fail "${EXTRA_ERROR_PREFIX}unknown optional extra '${extra}'; choose from: ${USER_OPTIONAL_EXTRAS}"
      ;;
  esac

  if extra_is_requested "$extra"; then
    return
  fi
  if [[ -z "$REQUESTED_EXTRAS" ]]; then
    REQUESTED_EXTRAS="$extra"
  else
    REQUESTED_EXTRAS="${REQUESTED_EXTRAS},${extra}"
  fi
}

parse_extra_list() {
  local remaining="$1" extra

  while [[ "$remaining" == *,* ]]; do
    extra="${remaining%%,*}"
    remaining="${remaining#*,}"
    add_requested_extra "$extra"
  done
  add_requested_extra "$remaining"
}

parse_installer_args() {
  # Arguments are processed left-to-right in a single pass: -h/--help prints
  # usage and exits 0 as soon as it is reached, so an invalid argument earlier
  # in argv still fails with rc=1 (it is reached first) while --help earlier
  # than an invalid argument still succeeds (the invalid one is never
  # reached). MORDRED_INSTALL_EXTRAS is resolved after this loop, so a --help
  # the loop reaches short-circuits before the environment variable is ever
  # parsed, and cannot itself fail before a command-line --help is honored.
  while (($#)); do
    case "$1" in
      -h | --help)
        usage
        exit 0
        ;;
      --uninstall)
        UNINSTALL=1
        shift
        ;;
      --dry-run | --yes | --purge-data | --remove-helper)
        UNINSTALL_ARGS+=("$1")
        shift
        ;;
      --with-extension)
        INSTALL_OPTION_SEEN="$1"
        parse_extra_list "extension,ethereum"
        shift
        ;;
      --with-telegram)
        INSTALL_OPTION_SEEN="$1"
        parse_extra_list "extension,telegram"
        shift
        ;;
      --extras)
        INSTALL_OPTION_SEEN="$1"
        if (($# < 2)) || [[ "$2" == -* ]]; then
          fail "--extras requires a comma-separated list"
        fi
        parse_extra_list "$2"
        shift 2
        ;;
      --extras=*)
        INSTALL_OPTION_SEEN="--extras"
        parse_extra_list "${1#*=}"
        shift
        ;;
      --all-extras)
        INSTALL_OPTION_SEEN="$1"
        parse_extra_list "$USER_OPTIONAL_EXTRAS"
        shift
        ;;
      --version)
        INSTALL_OPTION_SEEN="$1"
        if (($# < 2)) || [[ -z "$2" || "$2" == -* ]]; then
          fail "--version requires a version"
        fi
        REQUESTED_VERSION="$2"
        shift 2
        ;;
      --version=*)
        INSTALL_OPTION_SEEN="--version"
        REQUESTED_VERSION="${1#--version=}"
        if [[ -z "$REQUESTED_VERSION" ]]; then
          fail "--version requires a version"
        fi
        shift
        ;;
      --from-source)
        INSTALL_OPTION_SEEN="$1"
        if (($# < 2)) || [[ -z "$2" || "$2" == -* ]]; then
          fail "--from-source requires a directory"
        fi
        SOURCE_DIR="$2"
        shift 2
        ;;
      --from-source=*)
        INSTALL_OPTION_SEEN="--from-source"
        SOURCE_DIR="${1#--from-source=}"
        if [[ -z "$SOURCE_DIR" ]]; then
          fail "--from-source requires a directory"
        fi
        shift
        ;;
      --editable)
        INSTALL_OPTION_SEEN="$1"
        EDITABLE=1
        shift
        ;;
      --)
        shift
        if (($#)); then
          fail "unexpected argument: $1"
        fi
        ;;
      -*)
        fail "unknown option: $1"
        ;;
      *)
        fail "unexpected argument: $1"
        ;;
    esac
  done

  if ((UNINSTALL)); then
    if [[ -n "$INSTALL_OPTION_SEEN" ]]; then
      fail "--uninstall cannot be combined with ${INSTALL_OPTION_SEEN}"
    fi
    # Feature extras only matter for an install; a stale variable must not
    # break an uninstall.
    unset MORDRED_INSTALL_EXTRAS
    return
  fi
  if ((${#UNINSTALL_ARGS[@]})); then
    fail "${UNINSTALL_ARGS[0]} is only valid with --uninstall"
  fi

  # A whitespace-only value (e.g. a stale `export MORDRED_INSTALL_EXTRAS= ` in
  # a shell rc file) is treated like an unset one instead of failing on an
  # empty name. Errors from this list are prefixed so they name their actual
  # source: the caller never typed this value, so an unprefixed message like
  # "unknown optional extra" would look like it came from a flag.
  if [[ -n "$(trim_spaces "${MORDRED_INSTALL_EXTRAS:-}")" ]]; then
    EXTRA_ERROR_PREFIX="from MORDRED_INSTALL_EXTRAS: "
    parse_extra_list "$MORDRED_INSTALL_EXTRAS"
    # fail() exits, so this reset only matters for a future post-loop caller.
    EXTRA_ERROR_PREFIX=""
  fi
  unset MORDRED_INSTALL_EXTRAS
}

# Match the isolation used by Hermes's installer. A caller's Python or uv
# project settings must not redirect package discovery into another checkout,
# an ambient override must not redirect the download away from PyPI, and none
# of it may weaken how the download is verified. UV_NO_CONFIG only silences
# config *files*, so each variable has to be cleared by name.
unset PYTHONHOME PYTHONPATH UV_PYTHON UV_PROJECT_ENVIRONMENT
# Where packages come from.
unset UV_INDEX UV_INDEX_URL UV_DEFAULT_INDEX UV_EXTRA_INDEX_URL UV_FIND_LINKS
unset UV_INDEX_STRATEGY UV_NO_SOURCES UV_OFFLINE UV_CONFIG_FILE
# Whether they are verified, and which ones are eligible.
unset UV_INSECURE_HOST UV_NO_VERIFY_HASHES UV_SYSTEM_CERTS
unset UV_PRERELEASE UV_EXCLUDE_NEWER
# Where they land: the venv is chosen by --python, never by ambient state.
unset UV_SYSTEM_PYTHON UV_BREAK_SYSTEM_PACKAGES
export UV_NO_CONFIG=1

find_hermes_command() {
  # Hermes Desktop does not put `hermes` on PATH; its managed launcher lives
  # inside the agent checkout.
  local managed="${HERMES_HOME:-${HOME:-}/.hermes}/hermes-agent/.hermes/bin/hermes"
  if command -v hermes 2>/dev/null; then
    return
  fi
  if [[ -x "$managed" ]]; then
    printf '%s\n' "$managed"
  fi
}

python_from_managed_launcher() {
  # A managed (Hermes Desktop / bootstrap) launcher runs a standalone Python
  # that selects the active install environment at startup, so neither the
  # shebang nor the exec line names it. Ask the launcher itself: `site` prints
  # sys.path, which contains that environment's site-packages.
  local launcher="$1" line root
  while IFS= read -r line; do
    if [[ "$line" =~ \'(/[^\']+/venv)/lib/python[0-9.]+/site-packages\' ]]; then
      root="${BASH_REMATCH[1]}"
      if [[ -x "${root}/bin/python" ]]; then
        printf '%s\n' "${root}/bin/python"
        return
      fi
    fi
  done < <("$launcher" --run-module site 2>/dev/null | head -n 40)
}

find_uv() {
  # Hermes Desktop ships its own uv under <home>/tools without adding it to PATH.
  local candidate latest=""
  if command -v uv 2>/dev/null; then
    return
  fi
  for candidate in "${HERMES_HOME:-${HOME:-}/.hermes}"/tools/uv-*/uv; do
    [[ -x "$candidate" ]] && latest="$candidate"
  done
  if [[ -n "$latest" ]]; then
    printf '%s\n' "$latest"
  fi
}

launcher_first_line() {
  local launcher="$1" first_line
  first_line="$(head -n 1 "$launcher" 2>/dev/null || true)"
  printf '%s\n' "${first_line%$'\r'}"
}

looks_like_python() {
  local candidate="$1"
  [[ "${candidate##*/}" == python* ]] && [[ -x "$candidate" ]]
}

path_is_shell_safe() {
  # The generated launcher embeds this path inside a double-quoted `exec`. A
  # quote, backslash, backtick, `$` or newline would break out of that quoting
  # and turn the launcher into an injection point on every later invocation.
  case "$1" in
    *[\"\\\`\$]* | *$'\n'*) return 1 ;;
  esac
  return 0
}

python_from_shebang() {
  local launcher="$1"
  local first_line

  first_line="$(launcher_first_line "$launcher")"
  case "$first_line" in
    '#!'/*)
      first_line="${first_line#\#!}"
      # A console-script shebang contains one absolute interpreter path. Do not
      # guess when a wrapper adds flags or uses /usr/bin/env.
      if [[ "$first_line" != *[[:space:]]* ]] && looks_like_python "$first_line"; then
        printf '%s\n' "$first_line"
      fi
      ;;
  esac
}

python_from_exec_line() {
  # Hermes's own launcher is a bash wrapper, so its shebang only names bash:
  #
  #   #!/usr/bin/env bash
  #   unset PYTHONPATH
  #   unset PYTHONHOME
  #   exec "<venv>/bin/python" "<install>/hermes" "$@"
  #
  # The interpreter has to come from the exec line instead. Without this the
  # shebang probe never matches a real Hermes install and detection silently
  # falls through to the canonical directory.
  local launcher="$1"
  local line candidate

  case "$(launcher_first_line "$launcher")" in
    '#!'*) ;;
    *) return ;;
  esac

  while IFS= read -r line; do
    line="${line%$'\r'}"
    if [[ "$line" =~ ^[[:space:]]*exec[[:space:]]+\"(/[^\"]+)\" ]]; then
      candidate="${BASH_REMATCH[1]}"
      if looks_like_python "$candidate"; then
        printf '%s\n' "$candidate"
      fi
      return
    fi
  done < <(head -n 40 "$launcher" 2>/dev/null)
}

find_hermes_python() {
  # Prefer the environment behind the `hermes` the caller actually runs. The
  # canonical directory is only a fallback: when a second Hermes install shadows
  # it on PATH, installing into the canonical one would leave `hermes` and
  # `hermes-mordred` pointing at different environments.
  local launcher="$1"
  local hermes_home candidate detected managed

  if [[ -n "$launcher" ]]; then
    detected="$(python_from_shebang "$launcher")"
    if [[ -z "$detected" ]]; then
      detected="$(python_from_exec_line "$launcher")"
    fi
    if [[ -n "$detected" ]] && python_environment_root "$detected" >/dev/null; then
      printf '%s\n' "$detected"
      return
    fi
    managed="$(python_from_managed_launcher "$launcher")"
    if [[ -n "$managed" ]]; then
      printf '%s\n' "$managed"
      return
    fi
    if [[ -n "$detected" ]]; then
      printf '%s\n' "$detected"
      return
    fi
  fi

  # `${HOME}` bare would abort with `HOME: unbound variable` under `set -u`
  # instead of reaching the "install Hermes first" guidance below.
  hermes_home="${HERMES_HOME:-${HOME:-}/.hermes}"
  for candidate in \
    "${hermes_home}/hermes-agent/venv/bin/python3" \
    "${hermes_home}/hermes-agent/venv/bin/python"; do
    if [[ -x "$candidate" ]]; then
      printf '%s\n' "$candidate"
      return
    fi
  done
}

python_environment_root() {
  # Only install into an environment Mordred may own: a virtualenv, or a conda
  # environment for the rare hand-built Hermes install. Anything else is a
  # system or shared interpreter where `uv pip install` either refuses outright
  # or scatters console scripts outside the interpreter's own bin/.
  local python_path="$1" root
  root="$(cd "$(dirname "$python_path")/.." 2>/dev/null && pwd)" || return 1
  if [[ -f "${root}/pyvenv.cfg" || -d "${root}/conda-meta" ]]; then
    printf '%s\n' "$root"
    return 0
  fi
  return 1
}

version_at_least() {
  # Compare the major.minor ordinals only: the gate has never been patch-level,
  # and a trailing pre-release segment must not affect it. `10#` forces base 10
  # so a zero-padded segment is not read as octal.
  local have="$1" want="$2"
  local have_major have_minor want_major want_minor

  if [[ ! "$have" =~ ^([0-9]+)\.([0-9]+) ]]; then
    return 1
  fi
  have_major=$((10#${BASH_REMATCH[1]}))
  have_minor=$((10#${BASH_REMATCH[2]}))

  if [[ ! "$want" =~ ^([0-9]+)\.([0-9]+) ]]; then
    return 1
  fi
  want_major=$((10#${BASH_REMATCH[1]}))
  want_minor=$((10#${BASH_REMATCH[2]}))

  ((have_major > want_major || (have_major == want_major && have_minor >= want_minor)))
}

mordred_requirements() {
  # Print the installed hermes-mordred's requirements for the given extras,
  # markers evaluated, without hermes-agent itself.
  local hermes_python="$1" extras="$2"
  "$hermes_python" - "$DISTRIBUTION_NAME" "$extras" <<'PY' 2>/dev/null || true
import sys
from importlib.metadata import requires
from packaging.requirements import Requirement

extras = {e for e in sys.argv[2].split(",") if e}
for line in requires(sys.argv[1]) or []:
    req = Requirement(line)
    if req.name.lower().replace("_", "-") == "hermes-agent":
        continue
    if req.marker is None or any(req.marker.evaluate({"extra": e}) for e in extras | {""}):
        req.marker = None
        print(req)
PY
}

write_hermes_constraints() {
  # Pin every package already in Hermes's environment to its installed
  # version, so installing Mordred can add packages but never upgrade or
  # downgrade one Hermes depends on (its own lock pins them). Editable and
  # direct-URL entries (Hermes itself, a Mordred checkout) are left out, as
  # are Mordred's own distributions.
  local uv_bin="$1" hermes_python="$2" out="$3"
  "$uv_bin" pip freeze --python "$hermes_python" 2>/dev/null |
    grep -E '^[A-Za-z0-9][A-Za-z0-9._-]*==[^ ]+$' |
    grep -viE "^(${DISTRIBUTION_NAME}|${LEGACY_DISTRIBUTION_NAME})==" >"$out" || true
}

deps_are_consistent() {
  local uv_bin="$1" hermes_python="$2"
  "$uv_bin" pip check --python "$hermes_python" >/dev/null 2>&1
}

is_installer_launcher() {
  local path="$1"
  [[ -f "$path" ]] && head -n 5 "$path" 2>/dev/null | grep -qF \
    -e "$LAUNCHER_MARKER" -e "$LEGACY_LAUNCHER_MARKER"
}

write_launcher_file() {
  local target="$1" installed_cli="$2"
  cat >"$target" <<EOF && chmod 755 "$target"
#!/usr/bin/env bash
${LAUNCHER_MARKER} Safe to delete.
# Mirrors Hermes's own launcher: an ambient PYTHONPATH/PYTHONHOME must not
# redirect package discovery into a different checkout.
unset PYTHONPATH
unset PYTHONHOME
exec "${installed_cli}" "\$@"
EOF
}

install_launcher() {
  # Write a wrapper rather than a symlink. Hermes's own launcher unsets
  # PYTHONPATH/PYTHONHOME before exec; a bare symlink to the console script
  # would not, so an ambient PYTHONPATH could make `hermes-mordred` import a
  # different mordred_hermes than the one `hermes` loads. Owning the file also
  # means re-runs replace only launchers this installer wrote.
  local installed_cli="$1" hermes_launcher="$2"
  local link_dir link_path tmp

  if [[ -n "$hermes_launcher" ]]; then
    link_dir="$(dirname "$hermes_launcher")"
  else
    link_dir="${HOME}/.local/bin"
  fi
  link_path="${link_dir}/hermes-mordred"

  # A development checkout keeps `hermes` in the same venv bin/ that just
  # received the console script; there is nothing to wrap.
  if [[ "$link_path" -ef "$installed_cli" ]]; then
    printf '%s\n' "$installed_cli"
    return
  fi

  if { [[ -e "$link_path" ]] || [[ -L "$link_path" ]]; } && ! is_installer_launcher "$link_path"; then
    warn "not replacing ${link_path}; this installer did not create it"
    printf '%s\n' "$installed_cli"
    return
  fi

  if ! path_is_shell_safe "$installed_cli"; then
    warn "not generating a launcher: ${installed_cli} contains shell metacharacters"
    printf '%s\n' "$installed_cli"
    return
  fi

  # Every write below is checked explicitly. `set -e` does NOT apply here:
  # this function runs inside a command substitution, where errexit is
  # suppressed for the whole dynamic extent, so an unchecked failure would
  # run on to `mv` with an empty $tmp and bury the fact that the package
  # itself installed cleanly.
  if ! mkdir -p "$link_dir" 2>/dev/null ||
    ! tmp="$(mktemp "${link_dir}/.hermes-mordred.XXXXXX" 2>/dev/null)"; then
    warn "could not write to ${link_dir}; run ${installed_cli} directly"
    printf '%s\n' "$installed_cli"
    return
  fi

  if ! write_launcher_file "$tmp" "$installed_cli" || ! mv -f "$tmp" "$link_path"; then
    rm -f "$tmp"
    warn "could not write the launcher at ${link_path}; run ${installed_cli} directly"
    printf '%s\n' "$installed_cli"
    return
  fi
  printf '%s\n' "$link_path"
}

run_uninstall() {
  # The uninstall logic lives in the package (it has to decrypt what Mordred
  # encrypted before the package goes away), so find the CLI in Hermes's
  # environment exactly as an install would and hand over to it.
  local hermes_launcher hermes_python installed_cli
  hermes_launcher="$(find_hermes_command)"
  hermes_python="$(find_hermes_python "$hermes_launcher")"
  if [[ -z "$hermes_python" ]]; then
    fail "could not find Hermes's Python environment; nothing to uninstall"
  fi
  installed_cli="$(dirname "$hermes_python")/hermes-mordred"
  if [[ ! -x "$installed_cli" ]]; then
    printf 'To clean up what an earlier Mordred left behind (config.yaml entries,\n' >&2
    printf 'encrypted files), install it again, then re-run with --uninstall.\n' >&2
    fail "Mordred is not installed in Hermes's environment ($(dirname "$(dirname "$hermes_python")")); nothing to uninstall"
  fi
  info "running ${installed_cli} uninstall"
  # Piped from curl, this script's stdin is the script itself: give the CLI the
  # terminal so it can ask for confirmation.
  if [[ ! -t 0 ]] && { : </dev/tty; } 2>/dev/null; then
    exec "$installed_cli" uninstall ${UNINSTALL_ARGS[@]+"${UNINSTALL_ARGS[@]}"} </dev/tty
  fi
  exec "$installed_cli" uninstall ${UNINSTALL_ARGS[@]+"${UNINSTALL_ARGS[@]}"}
}

main() {
  local hermes_launcher hermes_python env_root uv_bin metadata hermes_version
  local platform platform_extra package_extras package_spec legacy_spec
  local installed_cli exposed_cli exposed_dir
  local legacy_metadata legacy_version
  local deps_were_consistent=0

  parse_installer_args "$@"
  if ((UNINSTALL)); then
    run_uninstall
  fi

  # Keep requirement operators, URLs, whitespace, and shell metacharacters out
  # of the package spec. uv remains the authority on whether the resulting
  # value is a valid/canonical PEP 440 version.
  if ((EDITABLE)) && [[ -z "$SOURCE_DIR" ]]; then
    fail "--editable requires --from-source"
  fi
  if [[ -n "$SOURCE_DIR" ]]; then
    if [[ -n "$REQUESTED_VERSION" ]]; then
      fail "--from-source and --version cannot be combined"
    fi
    SOURCE_DIR="$(cd "$SOURCE_DIR" 2>/dev/null && pwd)" || fail "--from-source: not a directory"
    if ! grep -Eq '^name[[:space:]]*=[[:space:]]*"'"${DISTRIBUTION_NAME}"'"' "${SOURCE_DIR}/pyproject.toml" 2>/dev/null; then
      fail "--from-source: ${SOURCE_DIR} is not a ${DISTRIBUTION_NAME} checkout"
    fi
  fi
  if [[ -n "$REQUESTED_VERSION" && ! "$REQUESTED_VERSION" =~ ^[0-9][0-9A-Za-z._!+-]*$ ]]; then
    fail "invalid version: ${REQUESTED_VERSION}"
  fi

  hermes_launcher="$(find_hermes_command)"
  hermes_python="$(find_hermes_python "$hermes_launcher")"
  if [[ -z "$hermes_python" ]]; then
    printf 'Install Hermes Agent first with its official installer:\n  %s\n' "$HERMES_INSTALL_COMMAND" >&2
    fail "could not find a Hermes-managed Python environment"
  fi

  if ! env_root="$(python_environment_root "$hermes_python")"; then
    printf 'Mordred installs into Hermes'"'"'s own environment and will not modify a\n' >&2
    printf 'system or shared interpreter.\n' >&2
    fail "the detected Hermes interpreter is not in a virtual environment: ${hermes_python}"
  fi

  uv_bin="$(find_uv)"
  if [[ -z "$uv_bin" ]]; then
    fail "uv is not on PATH; reload the shell after installing Hermes, then retry"
  fi

  if ! metadata="$("$uv_bin" pip show --python "$hermes_python" --no-python-downloads hermes-agent 2>/dev/null)"; then
    fail "the detected environment does not contain hermes-agent: ${env_root}"
  fi
  hermes_version="$(printf '%s\n' "$metadata" | awk -F ': ' '$1 == "Version" { print $2; exit }')"
  # A git/source Hermes (the Hermes Desktop layout) installs its package as
  # version 0.0.0; the real version comes from `hermes --version`.
  if [[ "$hermes_version" == "0.0.0" && -n "$hermes_launcher" ]]; then
    hermes_version="$("$hermes_launcher" --version 2>/dev/null | sed -n 's/^Hermes Agent v\([0-9][0-9.]*\).*/\1/p' | head -n 1)"
  fi
  if [[ -z "$hermes_version" ]]; then
    fail "could not determine the installed Hermes Agent version"
  fi
  if ! version_at_least "$hermes_version" "$MIN_HERMES_VERSION"; then
    printf 'Update Hermes Agent, then run this installer again:\n  hermes update\n' >&2
    fail "Hermes Agent ${hermes_version} is older than the required ${MIN_HERMES_VERSION}"
  fi

  platform="$(uname -s)"
  case "$platform" in
    Darwin)
      platform_extra='macos'
      ;;
    Linux)
      platform_extra='keyvault'
      ;;
    *)
      fail "unsupported platform ${platform}; Mordred currently supports macOS and Linux"
      ;;
  esac
  package_extras="${platform_extra}${REQUESTED_EXTRAS:+,${REQUESTED_EXTRAS}}"
  legacy_spec="${LEGACY_DISTRIBUTION_NAME}[${package_extras}]"
  local -a install_target
  if [[ -n "$SOURCE_DIR" ]]; then
    package_spec="${SOURCE_DIR}[${package_extras}]"
    if ((EDITABLE)); then
      install_target=(--editable "$package_spec")
    else
      # --reinstall-package: rebuild even when the checkout's version string
      # has not changed since the last source install.
      install_target=(--reinstall-package "$DISTRIBUTION_NAME" "$package_spec")
    fi
  elif [[ -n "$REQUESTED_VERSION" ]]; then
    # Retain the canonical-name floor even for exact pins so the permanent
    # 0.0.0.dev0 reservation stub can never replace a working installation.
    package_spec="${DISTRIBUTION_NAME}[${package_extras}]==${REQUESTED_VERSION},>=${MIN_MORDRED_VERSION}"
  else
    package_spec="${DISTRIBUTION_NAME}[${package_extras}]>=${MIN_MORDRED_VERSION}"
  fi
  if [[ -z "$SOURCE_DIR" ]]; then
    install_target=("$package_spec")
  fi

  # Mordred shares an environment with the running agent, so it can move a
  # dependency Hermes also pins. Record the state beforehand to report only a
  # conflict this install actually introduced.
  if deps_are_consistent "$uv_bin" "$hermes_python"; then
    deps_were_consistent=1
  fi

  info "Hermes Agent ${hermes_version} at ${hermes_python}"
  local constraints_file
  constraints_file="$(mktemp "${TMPDIR:-/tmp}/mordred-constraints.XXXXXX")" || fail "could not create a temporary file"
  # Global (not `local`): the EXIT trap runs after main() has returned.
  MORDRED_CONSTRAINTS_FILE="$constraints_file"
  trap 'rm -f "${MORDRED_CONSTRAINTS_FILE:-}"' EXIT
  write_hermes_constraints "$uv_bin" "$hermes_python" "$constraints_file"
  if [[ -z "$SOURCE_DIR" ]]; then
    info "checking ${package_spec} on PyPI"
    "$uv_bin" pip install \
      --python "$hermes_python" \
      --no-python-downloads \
      --upgrade-package "$DISTRIBUTION_NAME" \
      --no-deps \
      --dry-run \
      "$package_spec"
  fi

  legacy_version=""
  if legacy_metadata="$(
    "$uv_bin" pip show \
      --python "$hermes_python" \
      --no-python-downloads \
      "$LEGACY_DISTRIBUTION_NAME" 2>/dev/null
  )"; then
    legacy_version="$(printf '%s\n' "$legacy_metadata" | awk -F ': ' '$1 == "Version" { print $2; exit }')"
    if [[ -z "$legacy_version" ]]; then
      fail "could not determine the installed ${LEGACY_DISTRIBUTION_NAME} version"
    fi
    info "removing legacy ${LEGACY_DISTRIBUTION_NAME} ${legacy_version} before the ownership transfer"
    "$uv_bin" pip uninstall \
      --python "$hermes_python" \
      "$LEGACY_DISTRIBUTION_NAME"
  fi

  if [[ -n "$SOURCE_DIR" ]]; then
    info "installing ${DISTRIBUTION_NAME} from the local checkout ${SOURCE_DIR}$( ((EDITABLE)) && printf ' (editable)')"
  else
    info "installing ${package_spec} from PyPI"
  fi
  if ! "$uv_bin" pip install \
    --python "$hermes_python" \
    --no-python-downloads \
    --upgrade-package "$DISTRIBUTION_NAME" \
    --no-deps \
    "${install_target[@]}"; then
    if [[ -n "$legacy_version" ]]; then
      warn "canonical install failed; attempting to restore ${LEGACY_DISTRIBUTION_NAME} ${legacy_version}"
      if ! "$uv_bin" pip install \
        --python "$hermes_python" \
        --no-python-downloads \
        "${legacy_spec}==${legacy_version}"; then
        warn "automatic legacy-package restore failed; rerun the installer after connectivity is restored"
      fi
    fi
    fail "could not install ${DISTRIBUTION_NAME}"
  fi

  # Mordred itself went in with --no-deps: resolving its `hermes-agent`
  # requirement would re-resolve Hermes (whose published metadata can disagree
  # with the lock Hermes actually runs) and move Hermes's own packages. Install
  # only Mordred's other requirements, with every package Hermes already has
  # pinned to its installed version.
  local -a mordred_requirements=()
  local requirement
  while IFS= read -r requirement; do
    [[ -n "$requirement" ]] && mordred_requirements+=("$requirement")
  done < <(mordred_requirements "$hermes_python" "$package_extras")
  if ((${#mordred_requirements[@]})); then
    if ! "$uv_bin" pip install \
      --python "$hermes_python" \
      --no-python-downloads \
      --constraint "$constraints_file" \
      "${mordred_requirements[@]}"; then
      fail "could not install Mordred's dependencies without changing a package Hermes uses"
    fi
  fi

  if ((deps_were_consistent)) && ! deps_are_consistent "$uv_bin" "$hermes_python"; then
    warn "installing Mordred left conflicting dependencies in Hermes's environment"
    warn "inspect with: uv pip check --python ${hermes_python}"
  fi

  installed_cli="$(dirname "$hermes_python")/hermes-mordred"
  if [[ ! -x "$installed_cli" ]]; then
    fail "installation completed but ${installed_cli} was not created"
  fi
  exposed_cli="$(install_launcher "$installed_cli" "$hermes_launcher")"

  # Releases up to 0.1.0a20 registered six Hermes plugins (mordred_network, ...);
  # Mordred is now the single plugin `mordred`. Switch an existing config.yaml
  # off the old names so an upgraded install keeps loading Mordred. A no-op
  # unless an old name is listed; it never enables Mordred on its own.
  if ! "$installed_cli" plugins migrate --only-legacy; then
    warn "could not switch config.yaml to the single 'mordred' plugin; run: ${exposed_cli} plugins migrate"
  fi

  # Hermes Desktop: place the Mordred setup page (no keys are created here).
  local desktop_page=0
  # Placed whenever Hermes Desktop is installed ($HERMES_HOME/hermes-agent/apps/desktop)
  # or has created its plugin folder; the plugin also re-places it at start.
  if [[ -d "${HERMES_HOME:-$HOME/.hermes}/desktop-plugins" || -d "${HERMES_HOME:-$HOME/.hermes}/hermes-agent/apps/desktop" ]]; then
    if "$installed_cli" desktop install >/dev/null 2>&1; then
      desktop_page=1
    else
      warn "could not place the Mordred setup page for Hermes Desktop; run: ${exposed_cli} desktop install"
    fi
  fi

  printf '\nMordred is installed. Keys and policy were not changed.\n'
  if ((desktop_page)); then
    printf 'Hermes Desktop: restart it, then open "Mordred" in the sidebar to finish setup there.\n'
  fi
  printf 'Next, start the interactive setup:\n  %s configure\n' "$exposed_cli"
  exposed_dir="$(dirname "$exposed_cli")"
  case ":${PATH}:" in
    *":${exposed_dir}:"*) ;;
    *)
      printf '\nAdd %s to PATH to run the command by name.\n' "$exposed_dir"
      ;;
  esac
}

main "$@"
