"""Find what ``scripts/install.sh`` placed outside the Hermes home, for ``uninstall``.

The installer puts the package into the Python environment Hermes itself runs
(not a venv of Mordred's own), may write a ``hermes-mordred`` launcher next to
the ``hermes`` launcher, and ``keyvault enable-se`` / ``enable-tpm`` build a
native helper into ``~/.local/bin``. This module finds those the same way the
installer does, so ``uninstall`` removes exactly what was installed:

- **Hermes's environment** -- the ``hermes`` on ``PATH``, else the Hermes
  Desktop managed launcher ``<home>/hermes-agent/.hermes/bin/hermes``; its
  interpreter comes from the launcher's shebang, its ``exec "<python>"`` line,
  or (managed launcher) ``hermes --run-module site``; the fallback is the
  canonical ``<home>/hermes-agent/venv``. Only a virtualenv / conda
  environment qualifies, as in the installer.
- **uv** -- ``uv`` on ``PATH``, else Hermes Desktop's bundled
  ``<home>/tools/uv-*/uv``.
- **launchers** -- a ``hermes-mordred`` file is removed only when it carries
  the installer's marker line, or when it is a symlink to the console script
  that is being uninstalled (it would dangle afterwards). Anything else is
  reported and kept.
- **native helpers** -- ``mordred-hermes-sekey`` counts as Mordred-built only
  when ``codesign`` shows the ad-hoc signature and identifier the helper's
  ``build.sh`` produces.

Every probe here is read-only; the only command that changes anything is
:func:`uninstall_packages`.
"""

from __future__ import annotations

import os
import re
import shutil
import subprocess
import sys
from collections.abc import Callable, Sequence
from dataclasses import dataclass
from pathlib import Path

__all__ = [
    "DISTRIBUTIONS",
    "HELPER_NAMES",
    "HelperFinding",
    "HermesEnv",
    "LauncherFinding",
    "Runner",
    "classify_helpers",
    "classify_launchers",
    "default_runner",
    "detect_hermes_env",
    "uninstall_packages",
]

#: Marker lines the installer writes into a launcher (current and legacy name).
LAUNCHER_MARKERS: tuple[str, ...] = (
    "# Generated by the hermes-mordred installer.",
    "# Generated by the mordred-hermes installer.",
)
LAUNCHER_NAME = "hermes-mordred"
#: The canonical distribution and the pre-rename one the installer also removes.
DISTRIBUTIONS: tuple[str, ...] = ("hermes-mordred", "mordred-hermes")
HELPER_NAMES: tuple[str, ...] = ("mordred-hermes-sekey", "mordred-hermes-tpmkey")

#: ``(argv) -> CompletedProcess`` -- injectable for tests.
Runner = Callable[[Sequence[str]], "subprocess.CompletedProcess[str]"]
Which = Callable[[str], "str | None"]

_MANAGED_SITE = re.compile(r"'(/[^']+/venv)/lib/python[0-9.]+/site-packages'")
_EXEC_LINE = re.compile(r'^\s*exec\s+"(/[^"]+)"')
#: Environment variables that could point uv or Python somewhere other than the
#: environment named on the command line (the installer clears the same ones).
_SCRUBBED_ENV = (
    "PYTHONHOME",
    "PYTHONPATH",
    "UV_PYTHON",
    "UV_PROJECT_ENVIRONMENT",
    "UV_SYSTEM_PYTHON",
    "UV_BREAK_SYSTEM_PACKAGES",
    "UV_CONFIG_FILE",
)


def default_runner(argv: Sequence[str]) -> subprocess.CompletedProcess[str]:
    """Run ``argv`` with a scrubbed environment; never raises for a missing binary."""
    env = {key: value for key, value in os.environ.items() if key not in _SCRUBBED_ENV}
    env["UV_NO_CONFIG"] = "1"
    if sys.platform == "win32":
        env.update(PYTHONUTF8="1", PYTHONIOENCODING="utf-8")
    try:
        return subprocess.run(
            list(argv),
            capture_output=True,
            text=True,
            check=False,
            timeout=300,
            env=env,
            encoding="utf-8" if sys.platform == "win32" else None,
            errors="replace" if sys.platform == "win32" else None,
        )
    except (OSError, subprocess.SubprocessError) as exc:
        return subprocess.CompletedProcess(list(argv), 127, "", str(exc))


# -----------------------------------------------------------------------------
# Hermes's environment
# -----------------------------------------------------------------------------
@dataclass(frozen=True)
class HermesEnv:
    """Where the package lives and how to remove it."""

    launcher: Path | None
    python: Path | None
    uv: Path | None
    #: Distributions (of :data:`DISTRIBUTIONS`) installed in that environment.
    installed: tuple[str, ...]
    #: Why the environment or uv could not be used (empty when both were found).
    problem: str = ""

    @property
    def console_script(self) -> Path | None:
        return (
            self.python.parent / (LAUNCHER_NAME + (".exe" if sys.platform == "win32" else ""))
            if self.python is not None
            else None
        )

    @property
    def root(self) -> Path | None:
        if self.python is None:
            return None
        return _environment_root(self.python) if sys.platform == "win32" else self.python.parent.parent


def _looks_like_python(path: Path) -> bool:
    return path.name.startswith("python") and os.access(path, os.X_OK)


def _environment_root(python: Path) -> Path | None:
    """The venv / conda root of ``python``, or ``None`` for a system interpreter."""
    if sys.platform == "win32":
        from .._windows_runtime import environment_root

        return environment_root(python)
    root = python.parent.parent
    if (root / "pyvenv.cfg").is_file() or (root / "conda-meta").is_dir():
        return root
    return None


def _first_lines(path: Path, count: int) -> list[str]:
    try:
        with path.open(encoding="utf-8", errors="replace") as handle:
            return [line.rstrip("\r\n") for _, line in zip(range(count), handle, strict=False)]
    except OSError:
        return []


def find_hermes_launcher(home: Path, *, which: Which = shutil.which) -> Path | None:
    on_path = which("hermes.exe" if sys.platform == "win32" else "hermes")
    if on_path:
        return Path(on_path)
    managed = home / "hermes-agent" / ".hermes" / "bin" / ("hermes.exe" if sys.platform == "win32" else "hermes")
    return managed if managed.is_file() and os.access(managed, os.X_OK) else None


def _python_from_shebang(lines: list[str]) -> Path | None:
    if not lines or not lines[0].startswith("#!/"):
        return None
    interpreter = lines[0][2:]
    if any(ch.isspace() for ch in interpreter):
        return None
    candidate = Path(interpreter)
    return candidate if _looks_like_python(candidate) else None


def _python_from_exec_line(lines: list[str]) -> Path | None:
    if not lines or not lines[0].startswith("#!"):
        return None
    for line in lines:
        match = _EXEC_LINE.match(line)
        if match:
            candidate = Path(match.group(1))
            return candidate if _looks_like_python(candidate) else None
    return None


def _python_from_managed_launcher(launcher: Path, runner: Runner) -> Path | None:
    """Ask a Hermes Desktop launcher for its environment (``site`` prints sys.path)."""
    result = runner([str(launcher), "--run-module", "site"])
    for line in (result.stdout or "").splitlines()[:40]:
        match = _MANAGED_SITE.search(line)
        if match:
            python = Path(match.group(1)) / "bin" / "python"
            if os.access(python, os.X_OK):
                return python
    return None


def find_hermes_python(home: Path, launcher: Path | None, *, runner: Runner) -> Path | None:
    """The interpreter of Hermes's environment, found the way ``install.sh`` finds it."""
    if sys.platform == "win32":
        from .._windows_runtime import resolve_windows_python

        return resolve_windows_python(home, launcher, override=os.environ.get("MORDRED_HERMES_PYTHON"), runner=runner)
    if launcher is not None:
        lines = _first_lines(launcher, 40)
        detected = _python_from_shebang(lines) or _python_from_exec_line(lines)
        if detected is not None and _environment_root(detected) is not None:
            return detected
        managed = _python_from_managed_launcher(launcher, runner)
        if managed is not None:
            return managed
        if detected is not None:
            return detected
    for name in ("python3", "python"):
        candidate = home / "hermes-agent" / "venv" / "bin" / name
        if os.access(candidate, os.X_OK):
            return candidate
    return None


def find_uv(home: Path, *, which: Which = shutil.which) -> Path | None:
    if sys.platform == "win32" and "MORDRED_HERMES_UV" in os.environ:
        override = Path(os.environ["MORDRED_HERMES_UV"])
        return override if override.is_absolute() and override.suffix.lower() == ".exe" and override.is_file() else None
    on_path = which("uv.exe" if sys.platform == "win32" else "uv")
    if on_path:
        return Path(on_path)
    pattern = "uv-*/uv.exe" if sys.platform == "win32" else "uv-*/uv"
    bundled = sorted(path for path in (home / "tools").glob(pattern) if os.access(path, os.X_OK))
    return bundled[-1] if bundled else None


def _installed_distributions(uv: Path, python: Path, runner: Runner) -> tuple[str, ...]:
    found = []
    for name in DISTRIBUTIONS:
        result = runner([str(uv), "pip", "show", "--python", str(python), "--no-python-downloads", name])
        if result.returncode == 0:
            found.append(name)
    return tuple(found)


def detect_hermes_env(home: Path, *, which: Which = shutil.which, runner: Runner = default_runner) -> HermesEnv:
    """Locate Hermes's environment, uv, and which Mordred distributions it holds."""
    launcher = find_hermes_launcher(home, which=which)
    python = find_hermes_python(home, launcher, runner=runner)
    uv = find_uv(home, which=which)
    if python is None:
        return HermesEnv(launcher, None, uv, (), "could not find Hermes's Python environment")
    if _environment_root(python) is None:
        return HermesEnv(launcher, python, uv, (), f"{python} is not a virtual environment; not touching it")
    if uv is None:
        return HermesEnv(launcher, python, None, (), "uv was not found (not on PATH, not under <home>/tools)")
    return HermesEnv(launcher, python, uv, _installed_distributions(uv, python, runner))


def uninstall_packages(env: HermesEnv, *, runner: Runner = default_runner) -> tuple[bool, str]:
    """``uv pip uninstall`` every installed Mordred distribution. Returns ``(ok, output)``."""
    if not env.installed or env.uv is None or env.python is None:
        return True, ""
    result = runner([str(env.uv), "pip", "uninstall", "--python", str(env.python), *env.installed])
    output = "\n".join(part.strip() for part in (result.stdout, result.stderr) if part and part.strip())
    return result.returncode == 0, output


# -----------------------------------------------------------------------------
# Launchers
# -----------------------------------------------------------------------------
@dataclass(frozen=True)
class LauncherFinding:
    path: Path
    remove: bool
    reason: str


def _has_installer_marker(path: Path) -> bool:
    return any(marker in line for line in _first_lines(path, 5) for marker in LAUNCHER_MARKERS)


def _points_at(link: Path, target: Path) -> bool:
    try:
        raw = Path(os.readlink(link))
    except OSError:
        return False
    resolved = raw if raw.is_absolute() else link.parent / raw
    return os.path.normpath(resolved) == os.path.normpath(target)


def _classify_windows_launchers(home: Path) -> list[LauncherFinding]:
    from ._windows_install import is_owned

    path = home / "bin" / "hermes-mordred.ps1"
    if not (path.exists() or path.is_symlink()):
        return []
    owned = is_owned(path)
    reason = "verified installer receipt" if owned else "unknown Windows launcher; kept"
    return [LauncherFinding(path, owned, reason)]


def classify_launchers(env: HermesEnv, *, user_home: Path, hermes_home: Path | None = None) -> list[LauncherFinding]:
    """Every ``hermes-mordred`` launcher candidate, with whether ``uninstall`` removes it."""
    if sys.platform == "win32":
        return _classify_windows_launchers(hermes_home if hermes_home is not None else user_home / ".hermes")
    return _classify_posix_launchers(env, user_home=user_home)


def _classify_posix_launchers(env: HermesEnv, *, user_home: Path) -> list[LauncherFinding]:
    candidates: list[Path] = []
    if env.launcher is not None:
        candidates.append(env.launcher.parent / LAUNCHER_NAME)
    candidates.append(user_home / ".local" / "bin" / LAUNCHER_NAME)
    findings: list[LauncherFinding] = []
    seen: set[str] = set()
    console = env.console_script
    for path in candidates:
        key = os.path.normpath(path)
        if key in seen or not (path.exists() or path.is_symlink()):
            continue
        seen.add(key)
        if console is not None and os.path.normpath(path) == os.path.normpath(console):
            continue  # the console script itself; uv removes it
        if path.is_symlink():
            if console is not None and _points_at(path, console):
                if env.installed:
                    state = "which is being uninstalled"
                elif console.exists():
                    state = "the Mordred console script"
                else:
                    state = "which no longer exists (a dangling link)"
                findings.append(LauncherFinding(path, True, f"symlink to {console}, {state}"))
            else:
                findings.append(LauncherFinding(path, False, "a symlink the installer did not create"))
        elif path.is_file() and _has_installer_marker(path):
            findings.append(LauncherFinding(path, True, "written by the Mordred installer"))
        else:
            findings.append(LauncherFinding(path, False, "not written by the Mordred installer"))
    return findings


# -----------------------------------------------------------------------------
# Native helpers
# -----------------------------------------------------------------------------
@dataclass(frozen=True)
class HelperFinding:
    path: Path
    mordred_built: bool
    reason: str


def _sekey_is_mordred_built(path: Path, runner: Runner) -> tuple[bool, str]:
    result = runner(["codesign", "-dv", str(path)])
    details = f"{result.stdout or ''}\n{result.stderr or ''}"
    identifier = re.search(r"^Identifier=(\S+)", details, re.MULTILINE)
    if "Signature=adhoc" in details and identifier and identifier.group(1).startswith("mordred-hermes-sekey"):
        return True, "ad-hoc signed by the Mordred helper build"
    return False, "not the ad-hoc signed build from `keyvault enable-se`"


def classify_helpers(
    *, user_home: Path, platform: str, runner: Runner = default_runner, hermes_home: Path | None = None
) -> list[HelperFinding]:
    """The native helpers in ``~/.local/bin`` and whether Mordred built them."""
    if platform == "win32":
        from ._windows_install import is_owned

        home = hermes_home if hermes_home is not None else user_home / ".hermes"
        path = home / "bin" / "mordred-hermes-winkey.exe"
        if not (path.exists() or path.is_symlink()):
            return []
        owned = is_owned(path)
        return [HelperFinding(path, owned, "verified build receipt" if owned else "unknown Windows helper; kept")]
    findings: list[HelperFinding] = []
    for name in HELPER_NAMES:
        path = user_home / ".local" / "bin" / name
        if path.is_symlink() or not path.exists():
            if path.is_symlink():
                findings.append(HelperFinding(path, False, "a symlink, not the file the helper build installs"))
            continue
        if not path.is_file():
            findings.append(HelperFinding(path, False, "not a regular file"))
        elif name == "mordred-hermes-sekey" and platform == "darwin":
            built, reason = _sekey_is_mordred_built(path, runner)
            findings.append(HelperFinding(path, built, reason))
        else:
            findings.append(HelperFinding(path, True, "installed by the Mordred helper build"))
    return findings
