"""Content-bound ownership of public Windows executables and launchers.

These public artifacts contain no secrets. Receipts establish installer
ownership, not protection against hostile code running as the same user.
Windows publication requires the shared C1b trusted-parent filesystem; no
handwritten ACL or reparse-validation fallback is used.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib
import json
from collections.abc import Callable, Iterator
from contextlib import contextmanager
from pathlib import Path
from typing import Any, cast

_OWNER = "hermes-mordred-windows-installer-v1"
_WINKEY = "mordred-hermes-winkey.exe"
_LAUNCHER = "hermes-mordred.ps1"


def _confidential_opener() -> Callable[..., Any]:
    try:
        module = importlib.import_module("mordred_hermes._private_fs")
        opener = getattr(module, "open_confidential_directory", None)
    except ImportError:
        opener = None
    if opener is None:
        raise OSError("shared C1b trusted-parent filesystem capability required for Windows executable publication")
    return cast(Callable[..., Any], opener)


def _checked_missing(exc: OSError) -> bool:
    return getattr(exc, "reason", None) == "missing" and getattr(exc, "commit_state", None) == "not_committed"


def _native_owned(tx: Any, path: Path) -> bool:
    receipt = tx.read_bytes(receipt_path(path).name, max_bytes=4096)
    data = json.loads(receipt.decode("utf-8"))
    content = tx.read_bytes(path.name, max_bytes=64 * 1024 * 1024)
    return bool(data == {"owner": _OWNER, "name": path.name, "sha256": hashlib.sha256(content).hexdigest()})


@contextmanager
def _native_transaction(directory: Path, *, create: bool = False) -> Iterator[Any]:
    with _confidential_opener()(directory, create=create) as checked, checked.transaction() as tx:
        yield tx


def _native_publish(tx: Any, path: Path, content: bytes) -> Path:
    receipt = receipt_path(path)
    try:
        tx.stat(path.name)
    except OSError as exc:
        if not _checked_missing(exc):
            raise
        present = False
        try:
            tx.stat(receipt.name)
        except OSError as receipt_error:
            if not _checked_missing(receipt_error):
                raise
        else:
            raise OSError(f"orphan ownership receipt requires manual inspection: {receipt}")
    else:
        present = True
        if not _native_owned(tx, path):
            raise OSError(f"existing artifact is not verifiably owned; preserving {path}")
    writer = tx.replace_bytes if present else tx.create_bytes
    writer(path.name, content)
    verified = tx.read_bytes(path.name, max_bytes=64 * 1024 * 1024)
    if verified != content:
        raise OSError("published Windows artifact did not match intended bytes")
    data = {"owner": _OWNER, "name": path.name, "sha256": hashlib.sha256(verified).hexdigest()}
    writer(receipt.name, json.dumps(data, ensure_ascii=True).encode("utf-8"))
    if not _native_owned(tx, path):
        raise OSError("published Windows ownership receipt did not verify")
    return path


def receipt_path(path: Path) -> Path:
    return path.with_name(path.name + ".mordred-owner.json")


def is_owned(path: Path) -> bool:
    try:
        with _native_transaction(path.parent) as tx:
            return _native_owned(tx, path)
    except (OSError, ValueError, TypeError):
        return False


def _publish(path: Path, content: bytes) -> Path:
    with _native_transaction(path.parent, create=True) as tx:
        result = _native_publish(tx, path, content)
    return result


def publish_helper(source: Path, install_dir: Path, *, expected_sha256: str | None = None) -> Path:
    from .._private_fs import read_public_build_output

    content = read_public_build_output(source, max_bytes=64 * 1024 * 1024)
    if len(content) > 64 * 1024 * 1024 or not content.startswith(b"MZ"):
        raise OSError("helper build output must be a bounded Windows executable")
    if expected_sha256 is not None and hashlib.sha256(content).hexdigest() != expected_sha256.casefold():
        raise OSError("helper build output hash changed before publication")
    return _publish(install_dir / _WINKEY, content)


def _launcher_content(python: Path) -> bytes:
    literal = str(python).replace("'", "''")
    content = (
        "# Generated by the hermes-mordred installer.\n"
        "$ErrorActionPreference = 'Stop'\n"
        "Remove-Item Env:PYTHONHOME, Env:PYTHONPATH -ErrorAction SilentlyContinue\n"
        "$env:PYTHONUTF8 = '1'\n"
        "$env:PYTHONIOENCODING = 'utf-8'\n"
        "[Console]::OutputEncoding = New-Object Text.UTF8Encoding($false)\n"
        f"& '{literal}' -c 'from mordred_hermes.wizard.cli import main; raise SystemExit(main())' @args\n"
        "exit $LASTEXITCODE\n"
    )
    return b"\xef\xbb\xbf" + content.encode("utf-8")


def install_launcher(python: Path, install_dir: Path) -> Path:
    path = install_dir / _LAUNCHER
    content = _launcher_content(python)
    # Create only the default bin's final home parent through the capability;
    # arbitrary missing intermediate ancestors remain errors.
    with (
        _confidential_opener()(install_dir.parent, create=True),
        _native_transaction(install_dir, create=True) as tx,
    ):
        for suffix in (".exe", ".cmd", ".bat"):
            name = "hermes-mordred" + suffix
            try:
                tx.stat(name)
            except OSError as exc:
                if not _checked_missing(exc):
                    raise
            else:
                raise OSError(f"existing launcher takes precedence; preserving {install_dir / name}")
        result = _native_publish(tx, path, content)
    return result


def remove_owned(path: Path) -> None:
    with _native_transaction(path.parent) as tx:
        if not _native_owned(tx, path):
            raise OSError(f"artifact is no longer verifiably owned: {path}")
        metadata = tx.stat(path.name)
        receipt = receipt_path(path)
        receipt_metadata = tx.stat(receipt.name)
        tx.delete_file(path.name, expected_identity=metadata.identity)
        tx.delete_file(receipt.name, expected_identity=receipt_metadata.identity)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("kind", choices=("helper", "launcher"))
    parser.add_argument("source", type=Path)
    parser.add_argument("directory", type=Path)
    parser.add_argument("--expected-sha256")
    args = parser.parse_args()
    try:
        result = (
            publish_helper(args.source, args.directory, expected_sha256=args.expected_sha256)
            if args.kind == "helper"
            else install_launcher(args.source, args.directory)
        )
    except OSError as exc:
        parser.exit(1, f"Windows install failed: {exc}\n")
    print(json.dumps(str(result), ensure_ascii=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
